@port=3070
@jwt={{login.response.body.data.token}}


###
GET http://localhost:{{port}}/

###
GET http://localhost:{{port}}/api/v1/localhost:3070/api/v1/workouts?page=2&pageSize=30
Authorization: Bearer {{jwt}}

###
POST http://localhost:{{port}}/api/v1/workouts/
Content-Type: application/json
some-other-header: with my very personal information

{
"userPhoto": "https://clipartix.com/wp-content/uploads/2016/05/Happy-face-clip-art-smiley-face-clipart-3-clipartcow.jpg",
"user": "Dan Constance",
"date": "3/20/2023",
"workoutType": "Run",
"distance": "5280",
"duration": "15",
"pace": "352",
"calories": "350"
}


###
GET http://localhost:{{port}}/api/v1/workouts
###
DELETE http://localhost:{{port}}/api/v1/workouts/645289ae118dec1938bf749f

###
GET http://localhost:{{port}}/api/v1/workouts/search/

###
GET http://localhost:{{port}}/api/v1/users

###
GET http://localhost:{{port}}/api/v1/users/search/constand1@newpaltz.edu

###
POST http://localhost:{{port}}/api/v1/workouts/seed

###
DELETE http://localhost:{{port}}/api/v1/users/64511b5c97e964492d104fe5



###
POST http://localhost:3070/api/v1/users/login
Content-Type: application/json

{
    "email":"constand1@newpaltz.edu",
    "password":"dcon123"
}
###
GET http://localhost:3070/api/v1/workouts?page=2&pageSize=30
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDQ2Yzc5MDc3ZjczY2VhNWU0ODE4NmQiLCJuYW1lIjoiSm9obiBEb2UiLCJlbWFpbCI6ImpvaG5AZG9lLmNvbSIsInBob3RvIjoiaHR0cHM6Ly9yb2JvaGFzaC5vcmcvaGljdmVsZGljdGEucG5nP3NpemU9NTB4NTAmc2V0PXNldDEiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2ODIzNjM2MjcsImV4cCI6MTY4MjQ1MDAyN30.ybb286CRlkT8sbL9Nii7FIgbbzhy3QatKlVXVUMwei8

###
POST http://localhost:{{port}}/api/v1/users/seed

###
GET http://localhost:{{port}}/api/v1/users

###
# @name login
POST http://localhost:{{port}}/api/v1/users/login
Content-Type: application/json

{
    "email": "constand1@newpaltz.edu",
    "password": "dcon123"
}