@port=3070

###
GET http://localhost:{{port}}/

###
GET http://localhost:{{port}}/api/v1/workouts/

###
POST http://localhost:{{port}}/api/v1/workouts/
Content-Type: application/json
some-other-header: with my very personal information

{
"userPhoto": "https://clipartix.com/wp-content/uploads/2016/05/Happy-face-clip-art-smiley-face-clipart-3-clipartcow.jpg",
"user": "Dan Constance",
"date": "3/20/2023",
"workoutType": "Run",
"distance": "5280",
"duration": "15",
"pace": "352",
"calories": "350"
}
###
DELETE http://localhost:{{port}}/api/v1/workouts/645019f8506c92fd78e18228

###
GET http://localhost:{{port}}/api/v1/workouts/search/

###
GET http://localhost:3070/api/v1/users

###
POST http://localhost:{{port}}/api/v1/users/login
Content-Type: application/json

{
    "id":"1"
}